CREATE OR REPLACE PROCEDURE UpdateSalary(
    p_EmployeeID IN NUMBER,
    p_NewSalary  IN NUMBER
)
AS
BEGIN
    UPDATE Employees
    SET Salary = p_NewSalary
    WHERE EmployeeID = p_EmployeeID;

    IF SQL%ROWCOUNT = 0 THEN
        INSERT INTO ErrorLog (ErrorMessage, LogDate)
        VALUES ('Employee not found', SYSDATE);

        COMMIT;
        RETURN;
    END IF;

    COMMIT;
END;
/

EXEC UpdateSalary(99, 80000);

SELECT * FROM ErrorLog;

CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Message VARCHAR2(200),
    LogDate DATE
);

CREATE OR REPLACE PROCEDURE AddAuditLog(
    p_Message IN VARCHAR2
)
AS
BEGIN
    INSERT INTO AuditLog (Message, LogDate)
    VALUES (p_Message, SYSDATE);

    COMMIT;
END;
/

EXEC AddAuditLog('Salary updated successfully');

SELECT * FROM AuditLog;

CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest
AS
BEGIN
    UPDATE Accounts
    SET Balance = Balance + (Balance * 0.01);

    COMMIT;
END;
/

EXEC ProcessMonthlyInterest;

SELECT AccountID, Balance
FROM Accounts
ORDER BY AccountID;

CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(
    p_Department IN VARCHAR2,
    p_BonusPercent IN NUMBER
)
AS
BEGIN
    UPDATE Employees
    SET Salary = Salary + (Salary * p_BonusPercent / 100)
    WHERE Department = p_Department;

    COMMIT;
END;
/

EXEC UpdateEmployeeBonus('HR', 10);

SELECT EmployeeID, Name, Department, Salary
FROM Employees
WHERE Department = 'HR';



CREATE OR REPLACE PROCEDURE TransferFunds(
    p_FromAccount IN NUMBER,
    p_ToAccount   IN NUMBER,
    p_Amount      IN NUMBER
)
AS
    v_Balance NUMBER;
BEGIN
    SELECT Balance
    INTO v_Balance
    FROM Accounts
    WHERE AccountID = p_FromAccount;

    IF v_Balance >= p_Amount THEN
        UPDATE Accounts
        SET Balance = Balance - p_Amount
        WHERE AccountID = p_FromAccount;

        UPDATE Accounts
        SET Balance = Balance + p_Amount
        WHERE AccountID = p_ToAccount;

        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20003, 'Insufficient Balance');
    END IF;
END;
/

EXEC TransferFunds(2, 1, 100);

SELECT AccountID, Balance
FROM Accounts
ORDER BY AccountID;